version: "3.6"

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    container_name: todo_actix_pgdb
    environment:
      POSTGRES_USER: todo_actix
      POSTGRES_PASSWORD: todo_actix
      POSTGRES_DB: todo_actix
    ports:
    - 5433:5432
