name = "cloudflare_workers_rustwasm_helloworld"
type = "javascript"

# Whether you use `<NAME>.<SUBDOMAIN>.workers.dev` to test and deploy your worker.
workers_dev = true

compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
