version: '3.6'

services:
  warp_todo_crud_ex2_db:
    image: postgres:14-alpine
    restart: always
    container_name: warp_todo_crud_ex2_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5439:5432"
