[package]
authors = ["dxps <marius.ileana@gmail.com>"]
edition = "2021"
name = "rust_datatypes"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "string_literals"
path = "src/string_literals.rs"

[dependencies]
