[package]
edition = "2021"
name = "ui_g"
version = "0.1.0"

[dependencies]
confy = "0.4.0"
eframe = "0.15.0"
serde = {version = "1.0.130", features = ["derive"]}
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
