version: '3.6'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    container_name: test_pgdb
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "127.0.0.1:5437:5432"
