version: '3.6'

services:
  postgres_hyper_bb8_pgdb:
    image: postgres:14-alpine
    restart: always
    container_name: test_pgdb
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5437:5432"
